name: tests + mypy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest, mypy, codecov, pytest-cov, pandas
          pip install plotnine, matplotlib, scipy, scikit-learn
          pip install lightgbm, pyarrow, black, isort

      - name: MyPy Checks
        run: mypy miceforest

      - name: Black Formatting - Package
        run: black miceforest --check

      - name: Black Formatting - Tests
        run: black tests --check

      - name: Isort Checks
        run: isort miceforest --diff

      - name: Pytest
        run: pytest --cov-config .coveragerc --cov-report html --cov=miceforest

      - name: Code Cov
        run: codecov

